<?php

/**
 * CGTest v1.16.0 by Balint Toth [TBali]
 * A multi-language offline batch test runner for CodinGame (or other) solo I/O puzzles.
 *
 * configuration file
 */

declare(strict_types=1);

namespace TBali\CGTest;

return [
    // == The following default config options can be overriden:
    // 'dry-run' => false,
    // 'run-only' => false,
    // 'alt' => false,
    // 'ansi' => true,
    // 'verbose' => true,
    // 'stats' => false,
    // 'lang-versions' => false,
    // 'clean' => false,
    // 'create' => '',
    // 'test-case' => 'all',
    // 'slowThreshold' => 5, // in seconds
    // 'inputPath' => '.tests/input/',
    // 'inputPattern' => '%p_i%t.txt',
    // 'expectedPath' => '.tests/expected/',
    // 'expectedPattern' => '%p_e%t.txt',
    // 'outputPath' => '.tests/output/',
    // 'outputPattern' => '%p_o%t_%l.txt',
    // 'buildPath' => '.tests/temp/',
    // 'debugLog' => '.tests/output/_debug_log.txt',
    // 'buildLog' => '.tests/temp/_build_log.txt',
    // == Patterns available in 'inputPattern', 'expectedPattern', 'outputPattern':
    //     %l languageName
    //     %p puzzleName
    //     %t testIndex [01..99]
    // == Tests will be run in the following languages:
    //      Note: can be overriden via the '--lang=...' command-line option
    'languages' => array_merge(PHP_OS_FAMILY != 'Windows' ? [
        'bash',             // tested on Linux only
        // 'objective-c',   // untested
        'ocaml',            // tested on Linux only
        // 'swift',         // untested
    ] : [], [
        'c',
        'c#',
        'c++',
        'clojure',
        'd',
        'dart',
        'f#',
        'go',
        'groovy',
        'haskell',
        'java',
        'javascript',
        'kotlin',
        'lua',
        'pascal',
        'perl',
        'php',
        'python',
        'ruby',
        'rust',
        'scala',
        'typescript',
        'vb.net',
    // Additional languages, unsupported on CodinGame:
        // 'cobol',         // untested
        'fortran',
        // 'r',             // untested
    ]),
    // == Tests will be run for the following puzzles in ALL languages
    //      Note: can be overriden via command-line or in the per-language 'excludePuzzles' sections
    // 'puzzles' => [
    //     'path/' => [
    //         'puzzleName',
    //     ],
    // ],
    'puzzles' => [
        'puzzle/community/medium/' => [
            'medium_com_rubik',
        ],
    ],
    // == Tests will be run without test result evaluation for the following puzzles in ALL languages
    //      Note: can be overrriden in the per-language 'excludePuzzles' sections
    //      Note: the puzzle solution code must exit after reading turn #0 data to avoid infinite loop!
    // 'runOnlyPuzzles' => [
    //     'path/' => [
    //         'puzzleName',
    //     ],
    // ],
    'runOnlyPuzzles' => [
    ],
    // == The following per-language config options are available:
    // 'languageName' => [
    //     // IMPORTANT NOTE: if 'sourcePath' is given, it will OVERRIDE the 'path/' keys
    //     //   in the 'puzzles', 'runOnlyPuzzles' and 'includePuzzles' lists.
    //     'sourcePath' => 'language/',
    //     'sourceExtension' => '.lang',
    //     'codinGameVersion' => '',
    //     'versionCommand' => 'lang --version',
    //     'buildCommand' => '',
    //     'runCommand' => 'lang %s',
    //     'note' => '',
    //     'altVersionCommand' => '',
    //     'altBuildCommand' => '',
    //     'altRunCommand' => '',
    //     'altNote' => '',
    //     'cleanPatterns' => [
    //         'fileNameWithPathOrPattern',
    //     ],
    //     'excludePuzzles' => [
    //         'puzzleName',
    //     ],
    //     'includePuzzles' => [
    //         'path/' => [
    //             'puzzleName',
    //         ],
    //     ],
    //     'runOnlyPuzzles' => [
    //         'path/' => [
    //             'puzzleName',
    //         ],
    //     ],
    // ],
    // == Patterns available in 'buildCommand', 'runCommand', 'cleanPatterns':
    //     %l languageName
    //     %p puzzleName
    //     %o outputPath
    //     %b buildPath
    // == Patterns available in 'buildCommand', 'runCommand':
    //     %s sourceFileName (with path and extension)
    // == Additional test cases for a single language:
    'c++' => [
        'includePuzzles' => [
            'puzzle/cg/expert/' => [
                'expert_nintendo-sponsored-contest',        // puzzle available only in c++
            ],
        ],
    ],
    // == Additional test cases for a single language:
    'python' => [
        // 'sourcePath' => '', // uncomment if source code is not in 'php/' but in the keys, e.g. 'puzzle/cg/...'
        'includePuzzles' => [
            'codegolf/easy/' => [
                'codegolf_easy_ascii-art',
                'codegolf_easy_temperatures',
                'codegolf_easy_unary',
            ],
            'codegolf/medium/' => [
                'codegolf_medium_blunder-episode-1',
                'codegolf_medium_dwarfs-standing-on-the-shoulders-of-giants',
                'codegolf_medium_mayan-calculation',
                'codegolf_medium_network-cabling',
                'codegolf_medium_telephone-numbers',
            ],
            'codegolf/hard/' => [
                'codegolf_hard_blunder-episode-3',
                'codegolf_hard_genome-sequencing',
                'codegolf_hard_roller-coaster',
                'codegolf_hard_super-computer',
                'codegolf_hard_surface',
            ],
            'codegolf/expert/' => [
                'codegolf_expert_music-scores',
                'codegolf_expert_the-resistance',
            ],
            'puzzle/cg/event/' => [
                'event_summer-challenge-2023-q01',
                // 'event_summer-challenge-2023-q02',       // SQL puzzle
                'event_summer-challenge-2023-q03',
                'event_summer-challenge-2023-q05',
                // 'event_summer-challenge-2023-q06',       // SQL puzzle
                'event_summer-challenge-2023-q10',          // only tests 01-07 are included
                'event_winter-challenge-2023-q01',
                'event_winter-challenge-2023-q04',
                'event_winter-challenge-2023-q06',          // only tests 01-10 are included
                'event_winter-challenge-2023-q07',          // only tests 01-07 are included
                'event_spring-challenge-2024-q01',
                'event_spring-challenge-2024-q02',
                // 'event_spring-challenge-2024-q03',       // SQL puzzle
                'event_spring-challenge-2024-q04',
                'event_spring-challenge-2024-q06',
                // 'event_spring-challenge-2024-q07',       // SQL puzzle
                'event_spring-challenge-2024-q08',
                'event_spring-challenge-2024-q09',
            ],
            'puzzle/cg/easy/' => [
                'easy_cg_ascii-art',
                'easy_cg_defibrillators',
                'easy_cg_horse-racing-duals',
                'easy_cg_mime-type',
                'easy_cg_temperatures',
                'easy_cg_unary',
            ],
            'puzzle/cg/medium/' => [
                'medium_cg_blunder-episode-1',
                'medium_cg_conway-sequence',
                'medium_cg_dwarfs-standing-on-the-shoulders-of-giants',
                'medium_cg_mayan-calculation',
                'medium_cg_network-cabling',
                'medium_cg_scrabble',
                'medium_cg_stock-exchange-losses',
                'medium_cg_telephone-numbers',
                'medium_cg_the-gift',
                'medium_cg_war',
            ],
            'puzzle/cg/hard/' => [
                'hard_cg_blunder-episode-2',
                'hard_cg_blunder-episode-3',
                'hard_cg_cgx-formatter',
                'hard_cg_genome-sequencing',
                'hard_cg_roller-coaster',
                'hard_cg_super-computer',
                'hard_cg_surface',
                'hard_cg_tan-network',
                'hard_cg_winamax-sponsored-contest',
            ],
            'puzzle/cg/expert/' => [
                'expert_cg_music-scores',
                // 'expert_cg_nintendo-sponsored-contest',  // puzzle available only in c++
                'expert_cg_the-resistance',
            ],
            'puzzle/community/easy/' => [
                'easy_com_1-ngr-basic-radar',
                'easy_com_1d-bush-fire',
                'easy_com_1d-spreadsheet',
                'easy_com_2nd-degree-polynomial-simple-analysis',
                'easy_com_7-segment-scanner',
                'easy_com_10-pin-bowling-scores',
                'easy_com_111-rubiks-cube-movements',
                'easy_com_1000000000d-world',
                'easy_com_a-bit-of-accounting---lettering',
                'easy_com_a-bunny-and-carrots',
                'easy_com_a-childs-play',
                'easy_com_a-mountain-of-a-mole-hill',
                'easy_com_abcdefghijklmnopqrstuvwxyz',
                'easy_com_add-em-up',
                'easy_com_agent-x-mission-1-the-caesar-cipher',
                'easy_com_an-adventure-in-the-fantasy-world',
                'easy_com_anagram-to-break-the-code',
                'easy_com_annihilation',
                'easy_com_another-road-construction-site---1',
                'easy_com_are-the-clumps-normal',
                'easy_com_artificial-emotional-intelligence',
                'easy_com_ascii-art-the-drunken-bishop-algorithm',
                'easy_com_ascii-worms',
                'easy_com_asteroids',
                'easy_com_auto-pickup',
                'easy_com_azimut',
                'easy_com_balanced-ternary-computer-encode',
                'easy_com_ball-trajectory-predictor',       // removed puzzle
                'easy_com_bank-robbers',
                'easy_com_battle-of-heroes',
                'easy_com_benfords-law',
                'easy_com_bet-payout-calculator',           // removed puzzle
                'easy_com_binary-image',
                'easy_com_blackjack-solver',
                'easy_com_blending-colors',
                'easy_com_blowing-fuse',
                'easy_com_bob-the-ascii-teacher',           // removed puzzle
                'easy_com_body-weight-is-a-girls-secret',
                'easy_com_bouncing-simulator',
                'easy_com_brackets-extreme-ed',
                'easy_com_brick-in-the-wall',
                'easy_com_build-a-bookcase',
                'easy_com_bulk-email-generator',
                'easy_com_buzzle',
                'easy_com_by-train-or-by-car',
                'easy_com_caesar-is-the-chief',
                'easy_com_calculator',
                'easy_com_card-counting-when-easily-distracted',
                'easy_com_character-replacement-problem',
                'easy_com_cheap-choices',
                'easy_com_codongame',
                'easy_com_container-terminal',
                'easy_com_cosmic-love',
                'easy_com_count-as-i-count',
                'easy_com_count-your-coins',
                'easy_com_couples-picture-frame',
                'easy_com_crack-the-trio-code',
                'easy_com_crazy-list',
                'easy_com_create-the-longest-sequence-of-1s',
                'easy_com_create-turn-here-signs',
                'easy_com_credit-card-verifier-luhns-algorithm',
                'easy_com_crop-circles',
                'easy_com_cubic-bezier-curves',
                'easy_com_currency-conversion-challenge',   // removed puzzle
                'easy_com_darts',
                'easy_com_darts-checkout-routes',
                'easy_com_dead-mens-shot',
                'easy_com_decode-the-message',
                'easy_com_deus-hex-machina',
                'easy_com_die-handedness',
                'easy_com_digital-scoreboard',
                'easy_com_disordered-first-contact',
                'easy_com_distributing-candy',
                'easy_com_dolbears-law',
                'easy_com_dungeons-and-maps',
                'easy_com_embedded-chessboards',
                'easy_com_encryptiondecryption-of-enigma-machine',
                'easy_com_encryptiondecryption-software',   // removed puzzle
                'easy_com_equivalent-resistance-circuit-building',
                'easy_com_escape-the-madness',
                'easy_com_euclids-algorithm',
                'easy_com_euclids-algorithm-with-complex-numbers',
                'easy_com_extended-hamming-codes',
                'easy_com_faro-shuffle',
                'easy_com_fax-machine',
                'easy_com_feature-extraction',
                'easy_com_fibonaccis-rabbit',
                'easy_com_firecontrol',
                'easy_com_fix-the-networks',
                'easy_com_fix-the-spaces',
                'easy_com_flip-the-sign',
                'easy_com_frame-the-picture',
                'easy_com_furlongs-per-fortnight',
                'easy_com_fussy-fuzzy-matching',
                'easy_com_gdq---binary-coded-decimal-clock',
                'easy_com_genetics-and-computers---part-1',
                'easy_com_ghost-legs',
                'easy_com_gold-packing',
                'easy_com_graffiti-on-the-fence',
                'easy_com_happy-numbers',
                'easy_com_hidden-messages-in-images',
                'easy_com_histogram',
                'easy_com_hooch-clash',
                'easy_com_horse-racing-hyperduals',
                'easy_com_how-high-up-does-the-beer-go',
                'easy_com_how-time-flies',
                'easy_com_hunger-games',
                'easy_com_in-stereo',
                'easy_com_insert-to-string',
                'easy_com_interstellar',
                'easy_com_ipv6-shortener',
                'easy_com_is-that-a-possible-word',
                'easy_com_is-the-king-in-check-part-1',
                'easy_com_isbn-check-digit',
                'easy_com_island-escape',
                'easy_com_item-maker',
                'easy_com_jack-silver-the-casino',
                'easy_com_kangaroo-words',
                'easy_com_kiss-the-girls',
                'easy_com_largest-number',
                'easy_com_library-dependencies',
                'easy_com_logically-reasonable-inequalities',
                'easy_com_logic-gates',
                'easy_com_longest-coast',
                'easy_com_longest-road',
                'easy_com_low-resolution-whats-the-shape',
                'easy_com_lumen',
                'easy_com_magic-string',
                'easy_com_make-an-atari-font',
                'easy_com_mandelbrot-set-approximation',
                'easy_com_markov-text-generation',
                'easy_com_master-of-mayhem',
                'easy_com_match-dna-sequence',
                'easy_com_max-area',
                'easy_com_may-the-triforce-be-with-you',
                'easy_com_messed-up-mosaics',
                'easy_com_metric-units',
                'easy_com_minesweeper-level-generator',
                'easy_com_minimal-palindrome-distance',
                'easy_com_mirrors',
                'easy_com_monday-tuesday-happy-days',
                'easy_com_morellets-random-lines',
                'easy_com_mountain-map-convergence',
                'easy_com_mountain-map',
                'easy_com_moves-in-maze',
                'easy_com_murder-in-the-village',
                'easy_com_mystery-malfunction',             // removed puzzle
                'easy_com_nato-alphabets-odd-uncles',
                'easy_com_nature-of-quadrilaterals',
                'easy_com_nature-of-triangles',
                'easy_com_nd-vector-sorting',
                'easy_com_next-growing-number',
                'easy_com_nicholas-breakspeare-and-hugh-of-evesham',
                'easy_com_no-more-pythons-please',
                'easy_com_non-triple-numbers',
                'easy_com_number-derivation',
                'easy_com_number-formatting',
                'easy_com_number-of-digits',
                'easy_com_number-partition',
                'easy_com_object-insertion',
                'easy_com_odd-quad-out',
                'easy_com_offset-arrays',
                'easy_com_order-of-succession',
                'easy_com_organic-compounds',
                'easy_com_pachinko-jackpot',
                'easy_com_panel-count',
                'easy_com_park-pilot',
                'easy_com_parse-sql-queries',
                'easy_com_periodic-table-spelling',
                'easy_com_personal-best',
                'easy_com_pirates-treasure',
                'easy_com_playing-card-odds',
                'easy_com_popularity-of-each-activity',
                'easy_com_prefix-code',
                'easy_com_probability-for-dummies',
                'easy_com_production-pipeline',
                'easy_com_queen-control',
                'easy_com_random-walk',
                'easy_com_rectangle-partition',
                'easy_com_rectangular-block-spinner',
                'easy_com_remove-insert-statements',
                'easy_com_retaining-water',
                'easy_com_retro-typewriter-art',
                'easy_com_reverse-fizzbuzz',
                'easy_com_reverse-minesweeper',
                'easy_com_robot-reach',
                'easy_com_robot-show',
                'easy_com_rock-paper-scissors-lizard-spock',
                'easy_com_rocks-papers-scissors-es',
                'easy_com_rooks-movements',
                'easy_com_rotating-arrows',
                'easy_com_rugby-score',
                'easy_com_sand-fall',
                'easy_com_save-my-drone',
                'easy_com_saving-snoopy',
                'easy_com_score-a-bridge-deal',
                'easy_com_scrabble-score',
                'easy_com_self-driving-car-testing',
                // 'easy_com_sentence-tokenising',          // removed puzzle, unavailable
                'easy_com_shadow-casting',
                'easy_com_shikaku-skill-builder',
                'easy_com_shoot-enemy-aircraft',
                'easy_com_should-bakers-be-frugal',
                'easy_com_sign-programming-language',
                'easy_com_simple-ai-duels',
                'easy_com_simple-auto-scaling',
                'easy_com_simple-awale',
                'easy_com_simple-load-balancing',
                'easy_com_six-degrees-of-kevin-bacon',
                'easy_com_smooth',
                'easy_com_snail-run',
                'easy_com_snake-sort-2d',
                'easy_com_someones-acting-sus----',
                'easy_com_sparse-matmul',
                'easy_com_square-spiral-for-alien-contact',
                'easy_com_squash_pi',
                'easy_com_stall-tilt',
                'easy_com_street-fighter-level-i',
                'easy_com_substitution-encoding',
                'easy_com_sudoku-validator',
                'easy_com_sum-of-spirals-diagonals',
                'easy_com_stunning-numbers',
                'easy_com_survey-prediction',
                'easy_com_swatch-internet-time',
                'easy_com_sweet-spot',
                'easy_com_table-of-contents',
                'easy_com_tabloid-couple-names',
                'easy_com_tbr-out-of-control',
                'easy_com_teds-compiler',
                'easy_com_text-formatting',
                'easy_com_the-alien-business-of-cows',
                'easy_com_the-broken-editor',
                'easy_com_the-dart-101',
                'easy_com_the-electrician-apprentice',
                'easy_com_the-frog-jump-1',                 // removed puzzle
                'easy_com_the-helpdesk',
                'easy_com_the-leaking-bathtub',
                'easy_com_the-logo-beyond-c-and-c',
                'easy_com_the-michelangelo-code',
                'easy_com_the-mystic-rectangle',
                'easy_com_the-other-side',
                'easy_com_the-prime-twins---part-one',
                'easy_com_the-river-i-',
                'easy_com_the-river-ii-',
                'easy_com_the-travelling-salesman-problem',
                'easy_com_the-weight-of-words',
                'easy_com_tictactoe',
                'easy_com_tile-a-floor',
                'easy_com_tile-a-floor-differently',
                'easy_com_treasure-hunt',
                'easy_com_tree-paths',
                'easy_com_triangle-toggle',
                'easy_com_tricky-number-verifier',
                'easy_com_ukuleleguitar-converter',
                'easy_com_ulam-spiral',
                'easy_com_unique-prefixes',
                'easy_com_unit-fractions',
                'easy_com_van-ecks-sequence',
                'easy_com_vectors-in-variables-dimensions',
                'easy_com_video-assistant-referee',
                'easy_com_video-comments',
                'easy_com_walk-on-a-die',
                'easy_com_what-is-your-garden-worth',
                'easy_com_whats-so-complex-about-mandelbrot',
                'easy_com_where-am-i-going',
                'easy_com_wheres-wally',
                'easy_com_winning-parabola',                // removed puzzle
                'easy_com_word-search-for-programmers',
                'easy_com_wordle-colorizer',
                'easy_com_ww2-mortar-warfare',
                'easy_com_xml-mdf-2016',
                'easy_com_you-are-the-father-maury-povich-style',
                'easy_com_zeckendorf-representation-part-i',
                'easy_com_zhiwei-sun-squares',
            ],
            'puzzle/community/medium/' => [
                'medium_com_10101',
                'medium_com_16x16-sudoku',
                'medium_com_1d-snake-arrange',
                'medium_com_2048-scores',
                'medium_com_222-rubiks-cube-movements',
                'medium_com_24-game',
                'medium_com_2-5d-maze',
                'medium_com_2-player-game-on-a-calculator',
                'medium_com_3d-printer',
                'medium_com_3n-tiling',
                'medium_com_5d-chests',
                'medium_com_a-star-exercise',
                'medium_com_advanced-tree',
                'medium_com_agent-x-mission-2mysterious-cryptogram',
                'medium_com_all-operations-are-equal',
                'medium_com_anagrams',
                'medium_com_ancestors-descendants',
                'medium_com_army-ants',
                'medium_com_ascii-art-glass-stacking',
                'medium_com_ascii-art-with-logo-language',
                'medium_com_ascii-art-with-logo-language-part-2',
                'medium_com_ascii-cube',
                'medium_com_ascii-graph',
                'medium_com_ascii-snakes',
                'medium_com_assignments-are-boring',
                'medium_com_a-coin-guessing-game',
                'medium_com_a-story-to-go-in-circles',
                'medium_com_bag-of-balls',
                'medium_com_barcode-scanner',
                'medium_com_battleship',
                'medium_com_battle-tower',
                'medium_com_beach-volleyball',
                'medium_com_bijective-numeration',
                'medium_com_bin-packing',
                'medium_com_binary-search-tree-traversal',
                'medium_com_binary-sequence',
                'medium_com_binary-tree-visual',
                'medium_com_bingo',
                'medium_com_bit-count-to-limit',
                'medium_com_blood-types',
                'medium_com_bmp-compression',
                'medium_com_boarding-passes-ready',
                'medium_com_boggle-with-friends',
                'medium_com_bouncing-barry',
                'medium_com_box-of-cigars',
                'medium_com_brackets-enhanced-edition',
                'medium_com_brackets-extended-edition',
                'medium_com_brackets-ultimate-edition',
                'medium_com_bruce-lee',
                'medium_com_bulgarian-solitaire',
                'medium_com_bulls-and-cows',
                'medium_com_bust-speeding-vehicles',
                'medium_com_byte-pair-encoding',
                'medium_com_cards-castle',
                'medium_com_carmichael-numbers',
                'medium_com_catalytic-microparticles',
                'medium_com_cgfunge-interpreter',
                'medium_com_cgs-minifier',
                'medium_com_chain-reaction',
                'medium_com_chained-matrix-products',
                'medium_com_chebyshev-orbiting',
                'medium_com_christmas-tree',
                'medium_com_circular-automation-the-period-of-chaos',
                'medium_com_cistercian-numerals',           // removed puzzle
                'medium_com_coastline',
                'medium_com_code-breaker-puzzle',
                'medium_com_complicated-interpreter',
                'medium_com_condition-overshadowing',
                'medium_com_connect-the-hyper-dots',
                'medium_com_consecutive-balanced-substrings',
                'medium_com_constrained-latin-squares',
                'medium_com_continued-fractions',
                'medium_com_cooking-passion',
                'medium_com_count-as-i-count-2',
                'medium_com_counting-squares-on-pegs',
                'medium_com_count-of-primes-in-a-number-grid',
                'medium_com_cows-in-a-maze',
                'medium_com_criminal',
                'medium_com_crossword',
                'medium_com_custom-game-of-life',
                'medium_com_cylinders',
                'medium_com_data-compression-1',            // removed puzzle
                'medium_com_ddcg-mapper',
                'medium_com_de-fizzbuzzer',
                'medium_com_decimal-numbers-to-floating-numbers',
                'medium_com_depot-organization',
                'medium_com_derivative-time---part1',
                'medium_com_detective-geek',
                'medium_com_dev-friends',                   // removed puzzle
                'medium_com_dice-galaxy',
                'medium_com_dice-probability-calculator',
                'medium_com_digit-sum-successor',
                'medium_com_divide-the-factorial',
                'medium_com_divine',
                'medium_com_dominoes-path',
                'medium_com_domino-puzzle',
                'medium_com_drug-interactions',
                'medium_com_duck-hunt',
                'medium_com_dungeon-3d',
                'medium_com_duo-combinations',
                'medium_com_dynamic-sorting',
                'medium_com_elementary-cellular-automaton',
                'medium_com_elliptic-curve-cryptography',
                'medium_com_english-length-units-conversion',
                'medium_com_enigma---3-rotors-without-plugboard',
                'medium_com_entry-code',
                'medium_com_equalizing-arrays',
                'medium_com_equation-search',
                'medium_com_eratosthenes-wallpaper',
                'medium_com_european-rugby-champions-cup-ranking',
                'medium_com_excavating-palindromes',
                'medium_com_factorial-vs-exponential',
                'medium_com_fair-numbering',
                'medium_com_find-the-liars',
                'medium_com_find-the-missing-plus-signs-in-addition',
                'medium_com_find-the-replacement',
                'medium_com_finish-the-eight-queens',
                'medium_com_firewall-placement',
                'medium_com_fishing-with-a-stick',
                'medium_com_flood-fill-example',
                'medium_com_folding-a-note',
                'medium_com_folding-paper',
                'medium_com_format-string-validation',
                'medium_com_fractal-image-recognition',
                'medium_com_frequency-based-decryption',
                'medium_com_frobenius-coin-puzzle',         // removed puzzle
                'medium_com_frog-date',
                'medium_com_frog-exchange',
                'medium_com_fun-with-cgx-expressions',
                'medium_com_fun-with-set-theory',
                'medium_com_function-notation',
                'medium_com_futoshiki-solver',
                'medium_com_game-of-life',
                'medium_com_game-of-life-simulation',
                'medium_com_goldbachs-conjecture',
                'medium_com_goro-want-chocolate',
                'medium_com_go-competition',
                'medium_com_gravity',
                'medium_com_gravity-centrifuge',
                'medium_com_gravity-centrifuge-tuning',
                'medium_com_gravity-tumbler',
                'medium_com_green-valleys',
                'medium_com_guessing-digits',
                'medium_com_guessing-n-cheating',
                'medium_com_hacking-at-robbercity',
                'medium_com_halting-sequences',
                'medium_com_hexagonal-maze',
                'medium_com_hexagonal-maze---part2',
                'medium_com_hidden-word',
                'medium_com_holey-times',
                'medium_com_horse-hyperracing-hyperduals',
                'medium_com_hotel',
                'medium_com_how-many-roads-lead-to-rome',
                'medium_com_how-many-triangles-and-rectangles',
                'medium_com_html-table-cell-split',
                'medium_com_huffman-code',
                'medium_com_hunger',
                'medium_com_identify-a-simple-shape',
                'medium_com_identifying-data-structure',
                'medium_com_if-then-else',
                'medium_com_indented-to-xml-like',          // removed puzzle
                'medium_com_inside-area',
                'medium_com_inversion-count',
                'medium_com_ip-mask-calculating',
                'medium_com_is-the-king-in-check-part-2',
                'medium_com_join-the-dots',
                'medium_com_jumping-frog',
                'medium_com_jumping-frogs',
                'medium_com_kaprekars-routine',
                'medium_com_kids-blocks',
                'medium_com_killer-sudoku-solver',
                'medium_com_knights-jam',
                'medium_com_l-triominoes',
                'medium_com_langtons-ant',
                'medium_com_largest-binary-rectangle',
                'medium_com_length-of-syracuse-conjecture-sequence',
                'medium_com_level-of-nested-parentheses',
                'medium_com_lexiscramble-quest',
                'medium_com_light-bulbs',
                'medium_com_literary-alfabet-soupe',
                'medium_com_locked-in-gear',
                'medium_com_logic-gates-detective',
                'medium_com_longest-increasing-subsequence',
                'medium_com_lost-astronaut',
                'medium_com_lunar-lockout',
                'medium_com_magic-coloring',
                'medium_com_magic-square',
                'medium_com_magic-stones',
                'medium_com_markov-ants',
                'medium_com_mask-matching',
                'medium_com_maximum-sub-sequence',
                'medium_com_maze-for-the-champions',
                'medium_com_maze-w-teleporters-and-jumps',
                'medium_com_maze',
                'medium_com_mcxxxx-microcontroller-simulation',
                'medium_com_merlins-magic-square',
                'medium_com_micro-assembly',
                'medium_com_minesweeper',
                'medium_com_minimal-number-of-swaps',
                'medium_com_minimax-exercise',
                'medium_com_mitosis-mayhem',
                'medium_com_monthly-system',
                'medium_com_mosaic',
                'medium_com_mrs--knuth---part-i',
                'medium_com_mrs--knuth---part-ii',
                'medium_com_near-palindromes',
                'medium_com_needle-in-a-haystack',
                'medium_com_networking',
                'medium_com_next-car-license-plate',
                'medium_com_number-of-letters-in-a-number---binary',
                'medium_com_number-of-paths-between-2-points',
                'medium_com_number-of-triangles-enclosing-x',
                'medium_com_numeral-system',
                'medium_com_one-for-his-nobs',
                'medium_com_oneway-city',
                'medium_com_optical-link-failure-localization',
                'medium_com_optimized-coloring',
                'medium_com_othello',
                'medium_com_palindromic-decomposition',
                'medium_com_paper-labyrinth',
                'medium_com_particle-detection-with-cloud-chamber',
                'medium_com_partition-numbers',
                'medium_com_paving-with-bricks',
                'medium_com_photo-booth-transformation',
                'medium_com_pixel-polygons',
                'medium_com_place-the-parenthesis',
                'medium_com_plague-jr',
                'medium_com_playfair-cipher',
                'medium_com_plight-of-the-fellowship-of-the-ring',
                'medium_com_polydivisible-number',
                'medium_com_porcupine-fever',
                'medium_com_primitive-pythagorean-triples',
                'medium_com_propositions-in-freges-ideography',
                'medium_com_reconstruct-a-tree',
                'medium_com_remaining-card',
                'medium_com_reversed-look-and-say',
                'medium_com_risk-odds-calculator',
                // 'medium_com_rubik',                      // also in global section
                'medium_com_quaternion-multiplication',
                'medium_com_queneau-numbers',
                'medium_com_railway-station-clock',
                'medium_com_random-time-travel',
                'medium_com_rational-number-tree',
                'medium_com_rearrange-string-to-two-numbers',
                'medium_com_recurring-decimal-to-fraction',
                'medium_com_regular-polygons',
                'medium_com_remainder-fantasy',
                'medium_com_reverse-polish-notation',
                'medium_com_ring-the-bells',
                'medium_com_river-crossing',
                'medium_com_road-trip',
                'medium_com_robbery-optimization',
                'medium_com_rock-paper-scissors-war',
                'medium_com_rocket-engines',
                'medium_com_rod-cutting-problem',
                'medium_com_roman-sorting',
                'medium_com_rummikub-1',
                'medium_com_russian-dolls',
                'medium_com_sandpile-addition',
                'medium_com_scary-ride-at-the-haunted-mansion',
                'medium_com_seam-carving',
                'medium_com_self-checkout-machine',
                'medium_com_shape-outline',
                'medium_com_shikaku-solver',
                'medium_com_short-accounts-make-long-friends',
                'medium_com_simple-blur',
                'medium_com_simple-fraction-to-mixed-number',
                'medium_com_simplified-monopoly-turns-prediction',
                'medium_com_slim-sat',
                'medium_com_smile-frieze-cheese',
                'medium_com_smooth-factory',
                'medium_com_snake-encoding',
                'medium_com_solid-integer',
                'medium_com_spore-city-planner',
                'medium_com_sticky-keyboard',
                'medium_com_straddling-checkerboard-cryptography',
                'medium_com_string-balls',
                'medium_com_sudoku-solver',
                'medium_com_suguru-solver',
                'medium_com_sum-of-divisors',
                'medium_com_surakarta',
                'medium_com_target-firing',
                'medium_com_team-building',
                'medium_com_tennis-score',
                'medium_com_texas-holdem',
                'medium_com_text-alignment',
                'medium_com_thermal-flying-episode-1',
                'medium_com_these-romans-are-crazy',
                'medium_com_the-cash-register',
                'medium_com_the-experience-for-creating-puzzles',
                'medium_com_the-fastest',
                'medium_com_the-g-note',
                'medium_com_the-grand-festival---i',
                'medium_com_the-grand-festival---ii',
                'medium_com_the-hooch-clash-grouch',        // removed puzzle
                'medium_com_the-lost-child-episode-1',
                'medium_com_the-lost-files',
                'medium_com_the-optimal-urinal-problem',
                'medium_com_the-parking',
                'medium_com_the-polish-dictionary',
                'medium_com_the-prime-twins---part-two',
                'medium_com_the-sovereigns-game',
                'medium_com_the-stonemason',
                'medium_com_the-ultimate-test',
                'medium_com_the-urinal-problem',
                'medium_com_the-voucher',
                'medium_com_tiny-forest',
                'medium_com_train-passenger',
                'medium_com_tree-recognition',
                'medium_com_trits-balanced-ternary-computing',
                'medium_com_valid-brackets-in-code',
                'medium_com_various-number-spirals',
                'medium_com_virus-spreading-and-clustering',
                'medium_com_vote-counting',
                'medium_com_ways-to-make-change',
                'medium_com_were-going-in-circles',
                'medium_com_what-the-brainfuck',
                'medium_com_windmill-problem',
                'medium_com_wine-from-kalbodia---episode-1',
                'medium_com_word-chain-game',
                'medium_com_wordle-solution-regex',
                'medium_com_ye_-an_th_r-w_rd-se_rch',
            ],
            'puzzle/community/hard/' => [
                'hard_com_24-the-long-game',
                'hard_com_3d-ascii-cube',                   // removed puzzle
                'hard_com_7-segment-display',
                'hard_com_8086-assembler-part-i',
                'hard_com_advertisements',
                'hard_com_alternative-vote',
                'hard_com_apple-tree',
                'hard_com_ascii-art-qr-code',
                'hard_com_a-game-of-go',
                'hard_com_a-man-with-a-plan',
                'hard_com_bailey-borwein-plouffe-pi',
                'hard_com_balanced-levers',
                'hard_com_basic-decision-tree---1',
                'hard_com_basic-decision-tree---2',
                'hard_com_big-bang-theory---sheldons-array-puzzle',
                'hard_com_binary-neural-network---part-1',
                'hard_com_binary-permutations',
                'hard_com_boggle',
                'hard_com_breaking-apart',
                'hard_com_breaking-bifid',
                'hard_com_breakout',
                'hard_com_candies',
                'hard_com_castle-siege',
                'hard_com_cgs-next-top-model',
                'hard_com_cheat-solving',
                'hard_com_chess-board-analyzer',
                'hard_com_chess-cavalry',
                'hard_com_chess-moves-on-fen-position',
                'hard_com_closest-number',
                'hard_com_cloudy-weather',
                'hard_com_code-your-own-automaton2000-step-1',
                'hard_com_conditional-probabilities',
                'hard_com_connect-four',
                'hard_com_counter-attack',
                'hard_com_cryptarithm',
                'hard_com_dawg',
                'hard_com_derivative-time---part2',
                'hard_com_discrete-log-problem',
                'hard_com_disks-intersection',
                'hard_com_divisibility-of-fibonacci-numbers-sum',
                'hard_com_dominoes-solver',
                'hard_com_doubly-solved-rubiks-cube',
                'hard_com_drawing-polygons',
                'hard_com_dumbbells-solver',
                'hard_com_egyptian-multiplication',
                'hard_com_einsteins-riddle-solver',
                'hard_com_electrical-grid',
                'hard_com_elevator',
                'hard_com_encounter-surface',
                'hard_com_erdos-number',
                'hard_com_execution-circle',
                'hard_com_expand-the-polynomial',
                'hard_com_factorials-of-primes-decomposition',
                'hard_com_flower-beds',
                'hard_com_fold-and-cut',
                'hard_com_fractal-carpet',
                'hard_com_gerrymandering',
                'hard_com_google-interview---the-two-egg-problem',
                'hard_com_grid-climbing',
                'hard_com_hangman',
                'hard_com_hanoi-tower',
                'hard_com_harmless-rooks',
                'hard_com_her-majestys-well-shared-secret',
                'hard_com_highest-truncated-pyramid',
                'hard_com_hill-notation-and-hill-order',
                'hard_com_hit-the-road',
                'hard_com_hitori-solver',
                'hard_com_horn-sat-solver',
                'hard_com_inertia-ride',
                'hard_com_kakuro-solver',
                'hard_com_kgood',
                'hard_com_killer-sudoku-extreme-challenge',
                'hard_com_kolakoski-sequence',
                'hard_com_laser-and-mirrors',
                'hard_com_legendary-archer-octavius',
                'hard_com_lets-make-a-cheap-ascii-3d-engine',
                'hard_com_levenshtein-distance',
                'hard_com_longest-palindrome',
                'hard_com_m-a-r-i--and-the-crazy-factory',
                'hard_com_magic-count-of-numbers',
                'hard_com_magical-frog',
                'hard_com_map-colorations',
                'hard_com_mars-colonization',
                'hard_com_maximising-integers',
                'hard_com_max-rect',
                'hard_com_mind-cracker',
                'hard_com_mini-sudoku-solver',
                'hard_com_misere-nim',
                'hard_com_monte-carlo-tree-search-exercise',
                'hard_com_mrs--knuth---part-iii',
                'hard_com_musical-intervals',
                'hard_com_mystery-sums',
                'hard_com_neighbor-sum-grids',
                'hard_com_n-pearls-necklace',
                'hard_com_n-queens',
                'hard_com_nonogram-inversor',
                'hard_com_nugget-numbers',
                'hard_com_obsolete-programming',
                'hard_com_order-of-oopserations',
                'hard_com_paper-folding-curve',
                'hard_com_parsing-context-free-grammar',
                'hard_com_pascal-trapezoid',
                'hard_com_pedestrian-traffic',
                'hard_com_picture-puzzle',
                'hard_com_rocket-mice',
                'hard_com_rummikub-2',
                'hard_com_secret-message-decoding',
                'hard_com_sha-256-hash',
                'hard_com_simons-oracle',
                'hard_com_simple-cpu-emulation-1',
                'hard_com_simple-pascal-pl0-compiler',
                'hard_com_simple-safecracking',
                'hard_com_simplify-selection-ranges',
                'hard_com_sliding-maze-puzzle',
                'hard_com_snooker-ball-collision',
                'hard_com_solve-for-x',
                'hard_com_spreadsheet-labels',
                'hard_com_staircases',
                'hard_com_string-balls-ii',
                'hard_com_strobogrammatic-numbers',
                'hard_com_sum-of-odd',
                'hard_com_symbolic-system-of-equations',
                'hard_com_takuzu-solver',
                'hard_com_test-before-validate',
                'hard_com_tetris',
                'hard_com_tetris-floor',
                'hard_com_the-balanced-centrifuge-problem',
                'hard_com_the-beautiful-sequence',
                'hard_com_the-burglars-dilemna',
                'hard_com_the-empire-enigma',
                'hard_com_the-flight-of-birds',
                'hard_com_the-greatest-number',
                'hard_com_the-hidden-fortress',
                'hard_com_the-highest-building',
                'hard_com_the-holy-grail',
                'hard_com_the-hungry-duck---part-1',
                'hard_com_the-hungry-duck---part-2',
                'hard_com_the-max-surface-box',
                'hard_com_the-total-is-right-weird-edition',
                'hard_com_thomas-and-the-freight-cars',
                'hard_com_three-little-piggies',
                'hard_com_timer-for-clash-of-code',
                'hard_com_to-skys-edge',
                'hard_com_turing-machine',
                'hard_com_txt2html',
                'hard_com_universe-conquest',
                'hard_com_vortex',
                'hard_com_wall-street',
                'hard_com_wave-function-collapse-sans-shannon',
                'hard_com_who-dunnit',
                'hard_com_x-egg-problem',
                'hard_com_zergling-rush',
            ],
            'puzzle/community/expert/' => [
                'expert_com_25x25-sudoku',
                'expert_com_a-million-digits-of-pi',
                'expert_com_binary-neural-network---part-2',
                'expert_com_cg-chat-interpreter---part-1',
                'expert_com_chemical-equation-balancing',
                'expert_com_codindice',
                'expert_com_completed-mahjong-hands',
                'expert_com_cross-the-lines',
                'expert_com_cubax-folding',
                'expert_com_dungeon-designer',
                'expert_com_fill-the-square',
                'expert_com_flood-the-world',
                'expert_com_haunted-manor',
                'expert_com_heart-of-the-city',
                'expert_com_high-rise-buildings',
                'expert_com_hourglass',
                'expert_com_king-of-diamonds',              // removed puzzle
                'expert_com_mathematics-for-big-ears',
                'expert_com_minimax-simple-example',
                'expert_com_nurikabe',
                'expert_com_running-up-that-hill',
                'expert_com_prime-fractals-in-pascals-triangle',
                'expert_com_prime-transformations',
                'expert_com_recurring-decimals',
                'expert_com_skylines',
                'expert_com_sliding-puzzle',
                'expert_com_spy-the-spies',
                'expert_com_squares-order',
                'expert_com_the-barnyard',
                'expert_com_the-crime-scene',
                'expert_com_the-lucky-number',
                'expert_com_the-two-piles-difference',
                'expert_com_the-water-jug-riddle-from-die-hard-3',
                'expert_com_ticket-to-ride-europe',
                'expert_com_tiling-squares',
                'expert_com_unflood-the-world',
                'expert_com_unfolding-paper',
                'expert_com_when-pigs-fly',
                'expert_com_xorandor',
            ],
            'puzzle/own/hello-world/' => [
                'my_easy_com_hello-world',
            ],
            'puzzle/own/lets-go-to-the-cinema/' => [
                'my_medium_com_lets-go-to-the-cinema',
            ],
            'puzzle/own/source-code-analyser/' => [
                'my_medium_com_source-code-analyser',
            ],
        ],
        // == Tests will be run without test result evaluation for the following puzzles
        //      Note: the puzzle solution code must exit after reading turn #0 data to avoid infinite loop!
        'runOnlyPuzzles' => [
            // 'codegolf/easy/' => [
            //     'codegolf_easy_dont-panic',
            //     'codegolf_easy_power-of-thor',
            // ],
            // 'codegolf/medium/' => [
            //    'codegolf_medium_shadows-of-the-knight-episode-1',
            // ],
            // 'codegolf/hard/' => [
            //    'codegolf_hard_the-bridge-episode-2',
            //    'codegolf_hard_the-fall-episode-2',
            //    'codegolf_hard_the-labyrinth',
            //    'codegolf_hard_vox-codei-episode-1',
            // ],
            // 'codegolf/expert/' => [
            //    'codegolf_expert_mars-lander-episode-3',
            //    'codegolf_expert_shadows-of-the-knight-episode-2',
            //    'codegolf_expert_the-fall-episode-3',
            //    'codegolf_expert_vox-codei-episode-2',
            // ],
            'optim/cg/' => [
                'optim_cg_a-star-craft',
                'optim_cg_code-of-the-rings',
                'optim_cg_code-vs-zombies',
                'optim_cg_codingame-sponsored',
                'optim_cg_mars-lander',
                'optim_cg_selenia-city',
            ],
            'optim/community/' => [
                'optim_com_bender---episode-4',
                'optim_com_bulls-and-cows-2',
                'optim_com_cgfunge-prime',
                'optim_com_number-shifting',
                'optim_com_samegame',
                'optim_com_search-race',
                'optim_com_snake',
                'optim_com_travelling-salesman',
                'optim_com_vehicle-routing-problem',
                'optim_com_wordle',
            ],
            'optim/community/2048/' => [
                'optim_com_2048',
            ],
            'puzzle/cg/' => [
                'tutorial_onboarding',
            ],
            'puzzle/cg/event/' => [
                'event_summer-challenge-2023-q04',
                'event_summer-challenge-2023-q07',
                'event_summer-challenge-2023-q08',          // only tests 01-06 are included
                'event_summer-challenge-2023-q09',
                'event_winter-challenge-2023-q02',
                'event_winter-challenge-2023-q03',
                'event_winter-challenge-2023-q05',
                'event_spring-challenge-2024-q05',
                'event_spring-challenge-2025',
            ],
            'puzzle/cg/easy/' => [
                'easy_cg_mars-lander-episode-1',
                'easy_cg_power-of-thor-episode-1',
                'easy_cg_the-descent',
            ],
            'puzzle/cg/medium/' => [
                'medium_cg_death-first-search-episode-1',
                'medium_cg_dont-panic-episode-1',
                'medium_cg_mars-lander-episode-2',
                'medium_cg_shadows-of-the-knight-episode-1',
                'medium_cg_the-fall-episode-1',
                'medium_cg_there-is-no-spoon-episode-1',
            ],
            'puzzle/cg/hard/' => [
                'hard_cg_death-first-search-episode-2',
                'hard_cg_dont-panic-episode-2',
                'hard_cg_power-of-thor-episode-2',
                'hard_cg_the-bridge-episode-2',
                'hard_cg_the-fall-episode-2',
                'hard_cg_the-labyrinth',
                'hard_cg_there-is-no-spoon-episode-2',
                'hard_cg_vox-codei-episode-1',
            ],
            'puzzle/cg/expert/' => [
                'expert_cg_mars-lander-episode-3',
                'expert_cg_shadows-of-the-knight-episode-2',
                'expert_cg_the-fall-episode-3',
                'expert_cg_vox-codei-episode-2',
            ],
            'puzzle/community/easy/' => [
                'easy_com_catching-up',
            ],
            'puzzle/community/medium/' => [
                'medium_com_bobthescience-and-the-food-stack',
                'medium_com_can-you-save-the-forest---episode-1',
                'medium_com_cooperative-mate-with-rook',
                'medium_com_escaping-the-cat',
                'medium_com_find-the-winning-strategy',
                'medium_com_forest-fire',
                'medium_com_minesweeper-1',
                'medium_com_polyominoes',
                'medium_com_rush-hour',
                'medium_com_sky-maze-adventures-1',
                'medium_com_tetrasticks',
            ],
            'puzzle/community/hard/' => [
                'hard_com_11-puzzle',
                'hard_com_adversarial-mate-with-rook',
                'hard_com_binary-extension',
                'hard_com_blockout',
                'hard_com_can-you-save-the-forest---episode-2',
                'hard_com_freecell',
                'hard_com_jump-point-search---preprocessing',
                'hard_com_jump-point-search---runtime',
                'hard_com_sokoban',
            ],
            'puzzle/community/expert/' => [
                'expert_com_breach',
                'expert_com_space-maze',
            ],
        ],
    ],
];
// Note: last puzzle added on 25.04.22: 'medium_com_frog-date',
